version: "3"
volumes: 
  node_modules:
services:
  app:
    build:
      context: .
    container_name: web-container
    ports:
      - "12009:3008"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"